export const SEND_AIRTIME_REQUEST = "SEND_AIRTIME_REQUEST"
export const SEND_AIRTIME_SUCCESS = "SEND_AIRTIME_SUCCESS"
export const SEND_AIRTIME_FAIL = "SEND_AIRTIME_FAIL"

export const GET_RECIPIENTS_REQUEST = "GET_RECIPIENTS_REQUEST"
export const GET_RECIPIENTS_SUCCESS = "GET_RECIPIENTS_SUCCESS"
export const GET_RECIPIENTS_FAIL = "GET_RECIPIENTS_FAIL"

export const TOTAL_AIRTIME_USER_SENT_REQUEST = "TOTAL_AIRTIME_USER_SENT_REQUEST"
export const TOTAL_AIRTIME_USER_SENT_SUCCESS = "TOTAL_AIRTIME_USER_SENT_SUCCESS"
export const TOTAL_AIRTIME_USER_SENT_FAIL = "TOTAL_AIRTIME_USER_SENT_FAIL"
