export const SEND_AIRTIME_REQUEST = "SEND_AIRTIME_REQUEST"
export const SEND_AIRTIME_SUCCESS = "SEND_AIRTIME_SUCCESS"
export const SEND_AIRTIME_FAIL = "SEND_AIRTIME_FAIL"

export const GET_RECIPIENTS_REQUEST = "GET_RECIPIENTS_REQUEST"
export const GET_RECIPIENTS_SUCCESS = "GET_RECIPIENTS_SUCCESS"
export const GET_RECIPIENTS_FAIL = "GET_RECIPIENTS_FAIL"

export const TOTAL_AIRTIME_USER_SENT_REQUEST = "TOTAL_AIRTIME_USER_SENT_REQUEST"
export const TOTAL_AIRTIME_USER_SENT_SUCCESS = "TOTAL_AIRTIME_USER_SENT_SUCCESS"
export const TOTAL_AIRTIME_USER_SENT_FAIL = "TOTAL_AIRTIME_USER_SENT_FAIL"

export const GET_SMS_LIST_REQUEST = "GET_SMS_LIST_REQUEST"
export const GET_SMS_LIST_SUCCESS = "GET_SMS_LIST_SUCCESS"
export const GET_SMS_LIST_FAIL = "GET_SMS_LIST_FAIL"

export const SEND_SMS_REQUEST = "SEND_SMS_REQUEST"
export const SEND_SMS_SUCCESS = "SEND_SMS_SUCCESS"
export const SEND_SMS_FAIL = "SEND_SMS_FAIL"

export const TOTAL_SMS_REQUEST = "TOTAL_SMS_REQUEST"
export const TOTAL_SMS_SUCCESS = "TOTAL_SMS_SUCCESS"
export const TOTAL_SMS_FAIL = "TOTAL_SMS_FAIL"
